version: "3.3"
 
services:
 elasticsearch:
   container_name: elasticsearch
   build:
     context: elasticsearch/
   volumes:
     - type: volume
       source: elasticsearch
       target: /usr/share/elasticsearch/data
   ports:
     - "9200:9200"
     - "9300:9300"
   environment:
     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
     ELASTIC_PASSWORD: elasticpradipta
     discovery.type: single-node
   networks:
     - elk_stack
 
 logstash:
   container_name: logstash
   build:
     context: logstash/
   ports:
     - "5044:5044"
     - "5000:5000"
     - "9600:9600"
   environment:
     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
   networks:
     - elk_stack
   depends_on:
     - elasticsearch

 filebeat:
   container_name: filebeat
   image: filebeatimage
   networks:
    - elk_stack
# guide
# docker run -d --name filebeat -v /var/lib/docker/containers:/usr/share/dockerlogs/data -v /var/run/docker.sock:/var/run/docker.sock filebeatimage
   volumes:
     - /var/lib/docker/containers:/usr/share/dockerlogs/data:ro
     - /var/run/docker.sock:/var/run/docker.sock
  # depends_on:
  #   - elasticsearch
 
 kibana:
   container_name: kibana
   build:
     context: kibana/
   ports:
     - "5601:5601"
   networks:
     - elk_stack
   depends_on:
     - elasticsearch
     
 jenkins:
   build:
     context: jenkins/
   privileged: true
   user: root
   environment:
     JENKINS_OPTS: --argumentsRealm.roles.user=pradipta --argumentsRealm.passwd.admin=pradipta --argumentsRealm.roles.admin=admin
   ports:
     - 8083:8080
     - 50003:50000
   container_name: jenkins
   volumes:
     - ./jenkins_data:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
   networks:
     - elk_stack    
 
networks:
 elk_stack:
   driver: bridge
 
volumes:
 elasticsearch:
